Revamp nix flake
pinnacle-comp/pinnacle pull request #215
Opened 2024-04-22 03:42 UTC by nixith

I decided to go with [crane](https://github.com/ipetkov/crane) instead, it apparently has better caching capabilities. The check capabilities are nice as well if you ever want to add some stuff to gh actions, for example. If you ever add another cargo subprjoct  or some random directory stuff it might need some extra work but it should mostly be fine. Happy to explain, at least at a high level,  whatever is going on.

Also given how I did the commits it might be a good idea to just squash this down during the pull request, at least I think you can.

2024-04-24 23:54 UTC, Ottatop commented
Alright this should be unblocked, if it's ready then rebase/merge with main and request a review

2024-04-25 00:00 UTC, nixith commented
do we want to merge with the lua api complete or have that as a separate pull?

2024-04-25 00:03 UTC, Ottatop commented
Probably best to do it in a different pull considering the hell you're going through trying to make that work lol

2024-04-28 22:12 UTC, nixith commented
Alright, we now have functional nix builds! I think the `metaconfig.toml` writer needs to be fixed up, for now it just pulls from the user's directory, but it's completely functional otherwise. I have examples [here](https://github.com/nixith/pinnacle-example) in case anyone wants some.

2024-04-29 16:32 UTC, Ottatop commented
Missed a slash omegalul

I'll try to review the parts I can figure out sometime this week, got a lot of stuff to do currently.

2024-05-01 18:24 UTC, Ottatop requested changes

2024-05-01 18:24 UTC, Ottatop commented on api/lua/examples/default/default_config.lua
> +    local terminal = "kitty"
I'm gonna need a *very* good reason why this has been changed to kitty because I like alacritty better and I will die on that hill

2024-05-01 18:24 UTC, Ottatop commented on justfile
> +    cp -r "{{rootdir}}pinnacle-api-defs/protocol" "${proto_dir}"
```suggestion
    cp -r "{{rootdir}}/pinnacle-api-defs/protocol" "${proto_dir}"
```

Also line 35 hasn't been updated

2024-05-01 18:31 UTC, Ottatop commented
@LogicalOverflow Seeing as you're the other Nix person here, do you have anything to comment on regarding all this Nix stuff I'm not familiar with?

2024-05-01 23:49 UTC, nixith commented on api/lua/examples/default/default_config.lua
> +    local terminal = "kitty"
Ah, see, the reason is because I'm a creature of habit who forgot to remove that change before commiting. V easy remove lol

2024-05-02 08:21 UTC, LogicalOverflow reviewed
(I didn't look much into the lua stuff, because I don't know lua)

Overall, I think most of the hard stuff is done, i.e building pinnacle and the config. Only how the two are merged together, and how the `metaconfig.toml` is handled throughout, to produce a `pinnacle-with-config` looks incomplete to me.

2024-05-02 08:21 UTC, LogicalOverflow commented on flake.nix
> +  description = "Build a cargo workspace";
I assume this is a copy-paste error :)

2024-05-02 08:21 UTC, LogicalOverflow commented on flake.nix
> +            "${pkgs.wayland}/lib:${pkgs.libGL}/lib:${pkgs.libxkbcommon}/${pkgs.libglvnd}/lib:${pkgs.mesa.drivers}/lib";
`${pkgs.libxkbcommon}/${pkgs.libglvnd}/lib` should probably be `${pkgs.libxkbcommon}/lib:${pkgs.libglvnd}/lib`

2024-05-02 08:21 UTC, LogicalOverflow commented on flake.nix
>            runtimeDependencies = with pkgs; [
the `wlcs` wrapper script and `cargo-outdated` got lost along the way, I think

2024-05-02 08:21 UTC, LogicalOverflow commented on flake.nix
> +          inherit (pinnacleLib) pinnacleWithRust pinnacleWithLua;
Having these two functions directly in packages, breaks `nix flake check`, because that expects all the packages to be derivations. Maybe we can move them to `pinnacle.withRust` and `pinnacle.withLua` using `passthru`.

2024-05-02 08:21 UTC, LogicalOverflow commented on flake.nix
> +      inputs.rust-analyzer-src.follows = "";
What does this do? (I've never seen a follows set to `""`)

2024-05-02 08:21 UTC, LogicalOverflow commented on nix/lib/merge-pinnacle-config.nix
> +  # NOTE: as of now I can't figure out a way to check if a file exists in another derivaion.
This is probably not really possible at the nix level, i.e. in nix code, but you can probably use some bash in the `postBuild` on the `symlinkJoin` to select the correct `metaconfig.toml`.

2024-05-02 08:21 UTC, LogicalOverflow commented on nix/lib/merge-pinnacle-config.nix
> +    #(manifestDerivation) # currently treated as a function rather than a derivation, should be fixable.
Currently, the passed `manifest` just isn't used. Also, `symlinkJoin` might just fails, if there is a collision between the joined derivations (which would be the case if both manifests are there).

2024-05-02 08:21 UTC, LogicalOverflow commented on nix/lib/buildPinnacleRustConfig.nix
> +    ln $out/bin/${pname} $out/share/pinnacle/config/${pname};
I do find this structure in the derivation a bit weird, with the config being in both `share/pinnacle/config/pinnacle-config` and `bin/pinnacle-config`. I would expected only next to the `metaconfig.toml`.

2024-05-02 12:01 UTC, nixith commented
Pinnacle-with-config is partially working. For now it manages to get them all in the same closure and set up protobuf stuff, the main issue is that I can't figure out how to write from the toml generator to where I want correctly. It probably needs to be out of the symlink and linked in with ln manually if I had to guess, for now it uses the `metaconfig.toml` at the root of the config build directory.

2024-05-02 12:02 UTC, nixith commented
I think `metaconfig.toml`'s nix attrset should probably be moved into it's own lib output, that way people can debug that on its own, get type hints, etc. when this is all done I think nix has official doc comments now, so I'll go through and add them to make poking around for people a little easier as needed.

2024-07-14 18:10 UTC, KDanisme commented
Hi guys, any way I can help in this PR?
I really want to try out pinnacle, really like the concept.
@nixith If your busy I can pick off from where you left, or create a PR to your fork, LMK

2024-07-14 18:55 UTC, nixith commented
> Hi guys, any way I can help in this PR?
> I really want to try out pinnacle, really like the concept.
> @nixith If your busy I can pick off from where you left, or create a PR to your fork, LMK

Feel free to, I have been a little busy so the help is appreciated. If you also want to rework much of what I've done feel free. My solution relies on some wacky IFD that i've since learned is not great practice, but I really don't have a better way to conceive of this beyond having a directory to link to the configuration spot for Lia and 0 ideas on how to manage this without IFD for Rust. Thanks for pitching in!

2024-07-14 20:07 UTC, KDanisme commented
> > Hi guys, any way I can help in this PR?
> > I really want to try out pinnacle, really like the concept.
> > @nixith If your busy I can pick off from where you left, or create a PR to your fork, LMK
> 
> Feel free to, I have been a little busy so the help is appreciated. If you also want to rework much of what I've done feel free. My solution relies on some wacky IFD that i've since learned is not great practice, but I really don't have a better way to conceive of this beyond having a directory to link to the configuration spot for Lia and 0 ideas on how to manage this without IFD for Rust. Thanks for pitching in!

Happy help
Whenever you get the chance, I would love for a tldr on the issue you had here.
Im not really sure what exactly is the blocker here.
Tried going through the comments but couldn't really figure it out, especially with this being a new project and all.

2024-07-14 20:30 UTC, nixith commented
> > > Hi guys, any way I can help in this PR?
> > > I really want to try out pinnacle, really like the concept.
> > > @nixith If your busy I can pick off from where you left, or create a PR to your fork, LMK
> > 
> > Feel free to, I have been a little busy so the help is appreciated. If you also want to rework much of what I've done feel free. My solution relies on some wacky IFD that i've since learned is not great practice, but I really don't have a better way to conceive of this beyond having a directory to link to the configuration spot for Lia and 0 ideas on how to manage this without IFD for Rust. Thanks for pitching in!
> 
> Happy to help
> Whenever you get the chance, I would love for a tldr on the issue you had here.
> Im not really sure what exactly is the blocker here.
> Tried going through the comments but couldn't really figure it out, especially with this being a new project and all.

The tl;Dr is we need to wait for the lua or rust derivation to build flake-side, then wait for the user's configuration derivation to build, then finish building their config in place. I've learned since building this that this is generally considered bad practice, but it works for now. I think it was mostly style stuff that I never got around to fixing.

2025-09-19 05:48 UTC, Ottatop commented
Closing in favor of #352

2025-09-19 05:48 UTC, closed without merging